// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6ThPwpe-vNfNABxDqU1I-GBk_PuQmdc',
    appId: '1:339721710853:web:229e00026af31c61559b6c',
    messagingSenderId: '339721710853',
    projectId: 'sinefili-app',
    authDomain: 'sinefili-app.firebaseapp.com',
    storageBucket: 'sinefili-app.appspot.com',
    measurementId: 'G-72QDVSYXE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN_mAnsqQq2yKwxaPgOjspWgA1-JGrekk',
    appId: '1:339721710853:android:ebf25fe6755239c3559b6c',
    messagingSenderId: '339721710853',
    projectId: 'sinefili-app',
    storageBucket: 'sinefili-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt8BTqaCQkQwMpWAAmWzpD-zrPSmtpiN4',
    appId: '1:339721710853:ios:35c5a3fe09354eea559b6c',
    messagingSenderId: '339721710853',
    projectId: 'sinefili-app',
    storageBucket: 'sinefili-app.appspot.com',
    iosBundleId: 'com.example.sinefiliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt8BTqaCQkQwMpWAAmWzpD-zrPSmtpiN4',
    appId: '1:339721710853:ios:35c5a3fe09354eea559b6c',
    messagingSenderId: '339721710853',
    projectId: 'sinefili-app',
    storageBucket: 'sinefili-app.appspot.com',
    iosBundleId: 'com.example.sinefiliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS6ThPwpe-vNfNABxDqU1I-GBk_PuQmdc',
    appId: '1:339721710853:web:cc3d5c6d6a76404c559b6c',
    messagingSenderId: '339721710853',
    projectId: 'sinefili-app',
    authDomain: 'sinefili-app.firebaseapp.com',
    storageBucket: 'sinefili-app.appspot.com',
    measurementId: 'G-RY2NSHRQ03',
  );
}
